### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by maxoutrunner** [BSData/warpath-firefight#3]
Hello. I'd like to update the game files to the fresh errata and fix some things.

**Comment by amis92** [comment]
Hello! So sorry it took over 3 months, this issue got lost in my inbox and it seems the original maintainer is not around.

Are you still interested?

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
